modLoader="javafml"
loaderVersion="[36,)"
license="GPLv3"
[[mods]]
modId="scala3std"
version="3.5.1+A"
displayName="Scala3Std"
authors="H2Sxxa"
[[dependencies.scala3std]]
modId="forge"
mandatory=true
versionRange="[25,37)"
ordering="NONE"
side="BOTH"
[[dependencies.scala3std]]
modId="minecraft"
mandatory=true
versionRange="[1.13.2,1.17.0)"
ordering="NONE"
side="BOTH"