modLoader = "kotori_scala"
loaderVersion = "[36,)"
license = "GPLv3"

[[mods]]
modId = "scala3std"
version = "${version}"
displayName = "Scala3Std"
authors = "H2Sxxa"

[[dependencies.scala3std]]
modId = "forge"
mandatory = true
versionRange = "[25,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scala3std]]
modId = "minecraft"
mandatory = true
versionRange = "[1.13.2,)"
ordering = "NONE"
side = "BOTH"