modLoader = "javafml"
loaderVersion = "[25,)"
license = "GPL-3.0-only"
issueTrackerURL = "https://github.com/H2Sxxa/Scala3Std/issues"

[[mods]]
modId = "${modid}"
version = "${version}"
displayName = "${modname}"
authors = "H2Sxxa"
description = '''
Universal Minecraft ModLoader Scala 3 Runtime Provider.
'''

[[dependencies.'${modid}']]
modId = "neoforge"
type = "required"
versionRange = "[1.7.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.'${modid}']]
modId = "minecraft"
type = "required"
versionRange = "[1.13.2,)"
ordering = "NONE"
side = "BOTH"